"""Tests for the server-sent event encoder."""

import json
from datetime import datetime, timezone

from app.streaming.sse_encoder import SseEncoder


def parse_sse_event(value: str) -> tuple[str, dict]:
    """Parse one SSE event generated by SseEncoder."""
    assert value.endswith("\n\n")
    lines = value.removesuffix("\n\n").splitlines()

    assert len(lines) == 2
    assert lines[0].startswith("event: ")
    assert lines[1].startswith("data: ")

    event_name = lines[0].removeprefix("event: ")
    data = json.loads(lines[1].removeprefix("data: "))
    return event_name, data


def test_start_event() -> None:
    event_name, data = parse_sse_event(
        SseEncoder.start(
            trace_id=1001,
            conversation_id=2001,
        )
    )

    assert event_name == "start"
    assert data == {
        "traceId": 1001,
        "conversationId": 2001,
    }


def test_route_event() -> None:
    event_name, data = parse_sse_event(
        SseEncoder.route(
            intent="RAG_QA",
            need_rag=True,
            knowledge_base_id=3001,
        )
    )

    assert event_name == "route"
    assert data["intent"] == "RAG_QA"
    assert data["needRag"] is True
    assert data["knowledgeBaseId"] == 3001


def test_retrieval_event() -> None:
    event_name, data = parse_sse_event(
        SseEncoder.retrieval(
            candidate_count=20,
            rerank_count=10,
            context_document_count=6,
        )
    )

    assert event_name == "retrieval"
    assert data == {
        "candidateCount": 20,
        "rerankCount": 10,
        "contextDocumentCount": 6,
    }


def test_delta_preserves_chinese_and_newline() -> None:
    event_name, data = parse_sse_event(
        SseEncoder.delta("第一行\n第二行")
    )

    assert event_name == "delta"
    assert data == {"content": "第一行\n第二行"}


def test_final_event_supports_nested_data() -> None:
    event_name, data = parse_sse_event(
        SseEncoder.final(
            {
                "answer": "最终回答",
                "citations": [{"chunkId": 10}],
            }
        )
    )

    assert event_name == "final"
    assert data["answer"] == "最终回答"
    assert data["citations"] == [{"chunkId": 10}]


def test_error_and_done_events() -> None:
    error_name, error_data = parse_sse_event(
        SseEncoder.error(
            code="CHAT_STREAM_FAILED",
            message="model unavailable",
            trace_id=1001,
        )
    )
    done_name, done_data = parse_sse_event(
        SseEncoder.done(trace_id=1001)
    )

    assert error_name == "error"
    assert error_data["traceId"] == 1001
    assert done_name == "done"
    assert done_data == {"traceId": 1001}


def test_heartbeat_serializes_datetime() -> None:
    timestamp = datetime(
        2026,
        7,
        30,
        10,
        0,
        tzinfo=timezone.utc,
    )

    event_name, data = parse_sse_event(
        SseEncoder.heartbeat(timestamp)
    )

    assert event_name == "heartbeat"
    assert data == {
        "timestamp": "2026-07-30T10:00:00+00:00"
    }
