import type { EndpointConfig } from "./types";

export const endpoints: EndpointConfig[] = [
  {
    id: "tenant-create",
    group: "租户",
    title: "创建租户",
    method: "POST",
    target: "java",
    path: "/tenants",
    description: "创建一个企业租户，后续用户、知识库都挂在租户下。",
  },
  {
    id: "tenant-get",
    group: "租户",
    title: "查询租户",
    method: "GET",
    target: "java",
    path: "/tenants/{tenantId}",
    description: "根据租户 ID 查询租户详情。",
  },
  {
    id: "tenant-enabled",
    group: "租户",
    title: "启用租户列表",
    method: "GET",
    target: "java",
    path: "/tenants/enabled",
    description: "查询当前启用状态的租户。",
  },
  {
    id: "tenant-disable",
    group: "租户",
    title: "禁用租户",
    method: "PATCH",
    target: "java",
    path: "/tenants/{tenantId}/disable",
    description: "将租户状态改为禁用。",
  },
  {
    id: "user-create",
    group: "用户",
    title: "创建用户",
    method: "POST",
    target: "java",
    path: "/users",
    description: "在指定租户下创建用户。",
  },
  {
    id: "user-get",
    group: "用户",
    title: "查询用户",
    method: "GET",
    target: "java",
    path: "/users/{userId}",
    description: "根据用户 ID 查询用户详情。",
  },
  {
    id: "user-by-username",
    group: "用户",
    title: "按用户名查询",
    method: "GET",
    target: "java",
    path: "/users/by-username",
    description: "在指定租户内按 username 查询用户。",
  },
  {
    id: "user-disable",
    group: "用户",
    title: "禁用用户",
    method: "PATCH",
    target: "java",
    path: "/users/{userId}/disable",
    description: "将用户状态改为禁用。",
  },
  {
    id: "kb-create",
    group: "知识库",
    title: "创建知识库",
    method: "POST",
    target: "java",
    path: "/knowledge-bases",
    description: "创建知识库，服务端会从上下文补充租户和用户。",
  },
  {
    id: "kb-page",
    group: "知识库",
    title: "分页查询知识库",
    method: "GET",
    target: "java",
    path: "/knowledge-bases",
    description: "按关键词和分页参数查询知识库。",
  },
  {
    id: "kb-get",
    group: "知识库",
    title: "查询知识库",
    method: "GET",
    target: "java",
    path: "/knowledge-bases/{knowledgeBaseId}",
    description: "查询知识库详情。",
  },
  {
    id: "kb-update",
    group: "知识库",
    title: "更新知识库",
    method: "PATCH",
    target: "java",
    path: "/knowledge-bases/{knowledgeBaseId}",
    description: "更新知识库名称、描述、可见性。",
  },
  {
    id: "kb-delete",
    group: "知识库",
    title: "删除知识库",
    method: "DELETE",
    target: "java",
    path: "/knowledge-bases/{knowledgeBaseId}",
    description: "逻辑删除知识库。",
  },
  {
    id: "document-upload",
    group: "文档",
    title: "上传文档",
    method: "POST",
    target: "java",
    path: "/documents/upload",
    description: "上传文件到对象存储并登记文档元数据。",
  },
  {
    id: "document-register",
    group: "文档",
    title: "登记文档",
    method: "POST",
    target: "java",
    path: "/documents",
    description: "不上传文件，只登记已有文件元数据。",
  },
  {
    id: "document-get",
    group: "文档",
    title: "查询文档",
    method: "GET",
    target: "java",
    path: "/documents/{documentId}",
    description: "查询文档详情。",
  },
  {
    id: "document-list",
    group: "文档",
    title: "知识库文档列表",
    method: "GET",
    target: "java",
    path: "/documents/by-knowledge-base/{knowledgeBaseId}",
    description: "查询某个知识库下的文档列表。",
  },
  {
    id: "document-status",
    group: "文档",
    title: "更新解析状态",
    method: "PATCH",
    target: "java",
    path: "/documents/{documentId}/parse-status",
    description: "手动更新文档解析状态。",
  },
  {
    id: "document-delete",
    group: "文档",
    title: "删除文档",
    method: "DELETE",
    target: "java",
    path: "/documents/{documentId}",
    description: "逻辑删除文档。",
  },
  {
    id: "document-chunks",
    group: "文档",
    title: "查看 Chunk",
    method: "GET",
    target: "java",
    path: "/documents/{documentId}/chunks",
    description: "查看文档切分后的 Chunk 列表。",
  },
  {
    id: "task-get",
    group: "入库任务",
    title: "查询任务",
    method: "GET",
    target: "java",
    path: "/ingestion/tasks/{taskId}",
    description: "查询文档入库任务主表。",
  },
  {
    id: "task-steps",
    group: "入库任务",
    title: "查询任务步骤",
    method: "GET",
    target: "java",
    path: "/ingestion/tasks/{taskId}/steps",
    description: "查看解析、切分、向量化等步骤状态。",
  },
  {
    id: "task-process",
    group: "入库任务",
    title: "执行解析切分",
    method: "POST",
    target: "java",
    path: "/ingestion/tasks/{taskId}/process",
    description: "手动触发文档解析和文本切分。",
  },
  {
    id: "task-embedding",
    group: "入库任务",
    title: "执行 Chunk 向量化",
    method: "POST",
    target: "java",
    path: "/ingestion/tasks/{taskId}/embedding",
    description: "手动触发 Chunk 调 Python Embedding 并写入 pgvector。",
  },
  {
    id: "python-health",
    group: "Python",
    title: "Python 健康检查",
    method: "GET",
    target: "python",
    path: "/health",
    description: "检查 Python API 是否启动。",
  },
  {
    id: "python-embedding",
    group: "Python",
    title: "文本向量化",
    method: "POST",
    target: "python",
    path: "/api/embeddings",
    description: "直接调用 Python Embedding 接口。",
  },
];
